spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/storeTest
    username: root
    password:

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml